% This function rearranges the sp file generated by SpectreRF to an array
% type file and generate the sp data in array "OutputArray"
% "OutputArray" (Type: Array) = Result data array
% "Input_String" (Type: String) = Name of the input file (Before rearranged)
% "Output_String" (Type: String) = Name of the output file
% "n" (Type: Integer) = Number of ports
function OutputArray = Func_File_Arrangement(Input_String, Output_String, n)
    InputFile = fopen(Input_String);                                        % Open the orginal file from ocnPrint (Call it A)
    OutputFile = fopen(Output_String, 'w');                                 % Open a new file. Save new data to this file (Call it B)
    Count = 0;                                                              % Top 4 lines in File A are not desired
    while ~feof(InputFile)                                                  % Check End of File
        Line = fgetl(InputFile);                                            % Get line information
        Count = Count + 1;                                                  
        if Count > 4                                                        % Top 4 lines in File A are not desired
          	fprintf(OutputFile, '%s\n', Line);                              % Write data to File B
        	continue;                                                       % Move on to the next line (while)
        end
    end
    fclose(InputFile);
    fclose(OutputFile);
    
    % Begin: Turn the sp file into an array type
    Content = fileread(Output_String);
    if n == 2
        StrTemp = '%f complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) ';       % 5 items for 2 ports
        Parsed = textscan(Content,StrTemp);
        OutputArray_Temp = [Parsed{1,1}];
        for Count = 1:4                                                     % S Parameters (S11 S12 S21 S22)
        OutputArray_Temp = [OutputArray_Temp Parsed{1,2*Count}+i*Parsed{1,2*Count+1}];
        end
    end
    if n == 4
        StrTemp = '%f complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) complex( %f , %f ) ';       % 11 items for 4 ports
        Parsed = textscan(Content,StrTemp);
        OutputArray_Temp = [Parsed{1,1}];
        for Count = 1:10                                                    % S Parameters (S11 S12 S13 S14 S22 S23 S24 S33 S34 S44)
        OutputArray_Temp = [OutputArray_Temp Parsed{1,2*Count}+i*Parsed{1,2*Count+1}];
        end
    end
    
    OutputArray = OutputArray_Temp;
    % End: Turn the sp file into an array type
end